#!/bin/sh

FILES=$(fd ".*scrot[_]?([0-9]{3})?.png" -d 1)

for FILE in $FILES; do
    if [[ $1 == "-d" || $1 == "--delete" ]]; then
        rm $FILE
        echo "Deleted: $FILE"
    else
        echo "To delete: $FILE"
    fi
done
