#!/bin/sh

if [[ $1 == "delete" ]]; then
    find . -maxdepth 1 -regextype posix-extended -regex '.*scrot[_]?[0-9]{3}?.png' -delete
else
    find . -maxdepth 1 -regextype posix-extended -regex '.*scrot[_]?[0-9]{3}?.png'
fi
