#!/bin/sh

FILES=$(find . -maxdepth 1 -regextype posix-extended -regex '.*scrot[_]?[0-9]{3}?.png')

for FILE in $FILES; do
    if [[ $1 == "-d" || $1 == "--delete" ]]; then
        rm $FILE
        echo "Deleted: $FILE"
    else
        echo "To delete: $FILE"
    fi
done
