# General configuration
use_nerdfont = true
notify = true

[keybindings]
"Shift+q" = "quit"
"q" = "back"

# Gruvbox dark
[theme]
background = "default"
primary = "white"
secondary = "light black"
title = "green"
playing = "light green"
playing_bg = "black"
playing_selected = "#ebdbb2"
highlight = "magenta"
highlight_bg = "black"
error = "red"
error_bg = "black"
statusbar_progress = "magenta"
statusbar_bg = "black"
statusbar = "green"
cmdline = "blue"
cmdline_bg = "black"
search_match = "green"
